### ISSUE TITLE
A more friendly license for iOS?

### ISSUE THREAD

**Issue by bitcasasucks** [Softmotions/ejdb#176]
Have you considered using a more friendly license? I LOVE your project but we cannot use it on iOS and honor the LGPL license. 

Its not just LGPL, at one point we were considering making apps for the PS Vita and possibly windows app store among others but honoring the LGPL in these situations is torture.

**Comment by akaustel** [comment]
I agree. Would need more permissive license for closed source app. @adamansky if a more permissive license is out of the question, would there be a dual license option for commercial use?

**Comment by adamansky** [comment]
Hello! We are restricted by the LGPL license of Tokyo Cabinet (http://fallabs.com/tokyocabinet/ http://fallabs.com/license/) on which EJDB is based. I could contact to Mikio Hirabayashi (hiranin@gmail.com) - TC creator to get a pemissions, but since my previous attempts to contact Mikio i have no response from him.

**Comment by akaustel** [comment]
I see. They provide a commercial license for Kyoto Cabinet (KC) for 12000 USD, but somehow I doubt that TC is bringing in much license fees.

If you would get in contact with Mikio, it would settle the discussion. If you'd like, I can try contacting him, but I guess your word has more weight as the author of EJDB.

**Comment by adamansky** [comment]
I think the only way to avoid licence issues is to develop suchlike library which not dependent on tokyocabinet. EJDB2 will be released under permissive MIT licence #183 in next 3-6 months
