### ISSUE TITLE
When will db file ummap?

### ISSUE THREAD

**Issue by blueshame** [Softmotions/ejdb#351]
When EJDB run query the memory will grow up  as the db file will mmap.
So after finish query a long time, the process will sleep and db not close. 
I run this command which will release page cached. But why the memory does not decrease. When will db file ummap?
`echo 1 > /proc/sys/vm/drop_caches`

**Comment by adamansky** [comment]
Hi @blueshame Will answer a bit later

**Comment by adamansky** [comment]
You may run for example a `pmap -d <pid>` or `pmap -X <pid>` on your process.
You will get a complete process memory usage info. Also you will see some memory pages opposite to database file. Since a database file is memory mapped by program You may consider what is actual process memory usage occupies all of your memory but is not true because is Linux system will remove from RAM pages which was loaded by `mmap` if decided what not enough RAM. 

Take a look o this great article:
* https://techtalk.intersec.com/2013/07/memory-part-2-understanding-process-memory/ 
* https://techtalk.intersec.com/2013/07/memory-part-1-memory-types/
* https://gist.github.com/nh2/8c9fbf8cd9ad1ceba9a160cf50522679

Closing this as not a issue, please open related topic in forum https://github.com/Softmotions/ejdb/discussions
